# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(378, 329)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setGeometry(QtCore.QRect(10, 250, 291, 21))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(310, 250, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.name_box = QtWidgets.QCheckBox(self.centralwidget)
        self.name_box.setEnabled(True)
        self.name_box.setGeometry(QtCore.QRect(10, 40, 101, 20))
        self.name_box.setChecked(True)
        self.name_box.setObjectName("name_box")
        self.id_box = QtWidgets.QCheckBox(self.centralwidget)
        self.id_box.setEnabled(True)
        self.id_box.setGeometry(QtCore.QRect(10, 70, 101, 20))
        self.id_box.setChecked(True)
        self.id_box.setObjectName("id_box")
        self.creator_box = QtWidgets.QCheckBox(self.centralwidget)
        self.creator_box.setEnabled(True)
        self.creator_box.setGeometry(QtCore.QRect(120, 40, 101, 20))
        self.creator_box.setObjectName("creator_box")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setEnabled(True)
        self.textEdit.setGeometry(QtCore.QRect(10, 130, 361, 111))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.atts_box = QtWidgets.QCheckBox(self.centralwidget)
        self.atts_box.setEnabled(True)
        self.atts_box.setGeometry(QtCore.QRect(120, 70, 101, 20))
        self.atts_box.setObjectName("atts_box")
        self.jumps_box = QtWidgets.QCheckBox(self.centralwidget)
        self.jumps_box.setEnabled(True)
        self.jumps_box.setGeometry(QtCore.QRect(120, 100, 101, 20))
        self.jumps_box.setObjectName("jumps_box")
        self.diff_box = QtWidgets.QCheckBox(self.centralwidget)
        self.diff_box.setEnabled(True)
        self.diff_box.setGeometry(QtCore.QRect(10, 100, 111, 20))
        self.diff_box.setObjectName("diff_box")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 378, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GD STREAM"))
        self.label.setText(_translate("MainWindow", "Connecting to GeometryDash.exe..."))
        self.pushButton.setText(_translate("MainWindow", "Copy"))
        self.name_box.setText(_translate("MainWindow", "Level name"))
        self.id_box.setText(_translate("MainWindow", "Level ID"))
        self.creator_box.setText(_translate("MainWindow", "Creator"))
        self.atts_box.setText(_translate("MainWindow", "Attempts"))
        self.jumps_box.setText(_translate("MainWindow", "Jumps"))
        self.diff_box.setText(_translate("MainWindow", "Level difficulty"))
